global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090
  - job_name: avalanchego-machine
    static_configs:
     - targets:
       - localhost:9100
       labels:
         alias: machine
  - job_name: avalanchego
    metrics_path: /ext/metrics
    static_configs:
      - targets:
        - 127.0.0.1:9654
        - 127.0.0.1:9656
        - 127.0.0.1:9658
        - 127.0.0.1:9650
        - 127.0.0.1:9652
